services:
  - type: web
    name: fastapi-app
    env: python
    build:
      os: ubuntu-22.04
    buildCommand: |
      chmod +x build.sh && ./build.sh
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
