services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
